### PR TITLE
Issue19

### LINKED ISSUE #19: Search bar is a actually created, but it does not work right now.
A very very much important and needed feature is this search. 
One can design a basic search by searching the titles in the notesData. 

The main thing will be to where to show the search results?
And what to do when a user clicks on it?

I was thinking it to be like the search bar of whatsapp web.
image

### PR DESCRIPTION
**Pull request by prashant280920**
I have fixed #19 of searching notes @Signior-X

### CODE REVIEW

**Comment by Signior-X** [comment]
Bro yeh search to karr dega badiya
parr html ma update or dikhane ka?

**Comment by Signior-X** [comment]
Oh samjha mast sa to lagg raha hai

**Comment by Signior-X** [comment]
Bahot mast!!
just ek cheej karr dekh yadi tu search karta hai.... to uss time pe
jab tu click karre ek note ko kholne ke liye.... to search box ko empty karde

**Comment by prashant280920** [comment]
Issue of making search bar empty after searching notes is done. @Signior-X

**Pull request merged**
