### PR TITLE
Python script to minify codes

### LINKED ISSUE #39: python script to minify codes on deploy

### PR DESCRIPTION
**Pull request by khubi09**
fixes #39

### CODE REVIEW

**Comment by Signior-X** [comment]
The build.py file seems cool!

But the rest of the changes should be reverted. First of all I will suggest is to rebase your PR to current master.

**Comment by Signior-X** [comment]
do not create a new static folder
instead use the already created css and js folder in public folder to create the build folder.

**Comment by khubi09** [comment]
Done the required changes @Signior-X

**Comment by Signior-X** [comment]
Great we are good to merge.
Thanks for the changes.

This is the most time saving and required fix for the project! Voilla @khubi09

**Review by Signior-X — APPROVED** [review]

**Pull request merged**
